
package com.Minor.Project.model;

public enum NotificationType {
    STATUS_UPDATE,
    RESOLVED,
    ESCALATED,
    SYSTEM_ALERT,
    SLA_ALERT,
    ADMIN_NOTICE,
    HIGH_RISK,
    SLA_WARNING,
    SLA_BREACH,
    REPEAT_SUBMISSION,
    AREA_ALERT,
    ADMIN,
    AREA_RISK_ESCALATION,
    SPIKE_DETECTION,
    STAGNATION_ALERT
}
